#!/bin/bash

current_branch=$(git branch --show-current)

if echo $current_branch | grep -E 'wip|WIP' > /dev/null
then
  read -p "You're about to push a WIP branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
  echo
  if echo $REPLY | grep -E '^[Yy]$' > /dev/null
  then
    exit 0 # push will execute
  fi
  exit 1 # push will not execute
else
  exit 0 # push will execute
fi
